server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: job-service
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/api/jobs/**
        - id: application-service
          uri: lb://APPLICATION-SERVICE
          predicates:
            - Path=/api/applications/**
        - id: screening-service
          uri: lb://AI-SCREENING-SERVICE
          predicates:
            - Path=/api/screening/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:hireflow_default_secret_key_32chars!!}
